FROM {{ image }}

ENV GOTMPDIR=/opt/gotmpdir GOCACHE=/opt/gocache
RUN mkdir -p /opt/gotmpdir && chown {{ uid_gid }} /opt/gotmpdir
RUN mkdir -p /opt/gocache && chown {{ uid_gid }} /opt/gocache

{{ set_user_and_home_dir }}

RUN go mod init temp
{% if dependencies %}
RUN go get {{ dependencies }}
{% endif %}

{{ set_build_id }}

COPY --chown={{ uid_gid }} . .

RUN go build

CMD ["./temp"]
