FROM {{ image }}

ENV GOTMPDIR=/opt/gotmpdir GOCACHE=/opt/gocache
RUN mkdir -p /opt/gotmpdir && chown {{ uid_gid }} /opt/gotmpdir
RUN mkdir -p /opt/gocache && chown {{ uid_gid }} /opt/gocache

{{ set_user_and_home_dir }}

RUN go mod init temp
{% if dependencies %}
RUN go get {{ dependencies }}
{% endif %}

COPY --chown={{ uid_gid }} {{ main_file }} .
{% if fn_file %}
COPY --chown={{ uid_gid }} {{ fn_file }} .
{% endif %}
{% for file in files %}
COPY --chown={{ uid_gid }} {{ file.path }} ./files/{{ file.path }}
{% endfor %}

RUN go build

CMD ["./temp"]
