/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/code/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run code
         * @description Run a one-off script with the given parameters and stream the output
         */
        post: operations["run_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/function": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List functions
         * @description List each function's info and status
         */
        get: operations["list_functions"];
        put?: never;
        /**
         * Create function
         * @description Create a new function
         */
        post: operations["create_function"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/function/{name}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get function info
         * @description Get function info and status
         */
        get: operations["get_function"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/function/{name}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get function details
         * @description Get full function details and code
         */
        get: operations["get_function_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/function/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update function
         * @description Modify a saved function
         */
        post: operations["update_function"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/function/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run function
         * @description Run a saved function with the given inputs
         */
        post: operations["run_function"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/function/{name}/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run function
         * @description Run a saved function with the given inputs and stream the output
         */
        post: operations["run_function_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Options for the code runner */
        CodeRunnerInput: {
            /** @description The code to run */
            code: string;
            /** @description Language of the code */
            lang: components["schemas"]["CodeRunnerLanguage"];
            /**
             * @description Dependencies for the code execution. Versions and features can be specified
             *     depending on the language's package manager.
             * @example [
             *       "lodash"
             *     ]
             * @example [
             *       "serde=1.0",
             *       "tokio=1.0",
             *       "--features",
             *       "serde/derive"
             *     ]
             */
            dependencies?: string[] | null;
            /**
             * @description Files for the code execution. These files will be available to the code
             *     under the `./files` directory.
             */
            files?: components["schemas"]["CodeRunnerFile"][] | null;
            /**
             * Format: uint32
             * @description Timeout for the code execution in seconds
             * @default 60
             */
            timeout: number;
            /**
             * Format: uint32
             * @description Memory limit for the code execution in megabytes
             * @default 256
             */
            mem_limit_mb: number;
            /**
             * Format: float
             * @description CPU quota (1.0 = 1 CPU core)
             * @default 0.5
             */
            cpu_limit: number;
        };
        /**
         * @description Supported languages for the code runner
         * @enum {string}
         */
        CodeRunnerLanguage: "bash" | "go" | "javascript" | "python" | "rust" | "typescript";
        CodeRunnerFile: {
            /**
             * @description Path of the file relative to the `./files` directory. Must be
             *     a relative path, and cannot contain `..` or `.`
             * @example file.txt
             * @example foo/file.txt
             */
            path: string;
            /** @description Base64 encoded content of the file */
            content: string;
        };
        /** @description Chunk of the code runner stream output */
        CodeRunnerChunk: {
            /** @constant */
            event: "info";
            data: string;
        } | {
            /** @constant */
            event: "debug";
            data: string;
        } | {
            /** @constant */
            event: "stdout";
            data: string;
        } | {
            /** @constant */
            event: "stderr";
            data: string;
        } | {
            /** @constant */
            event: "error";
            data: components["schemas"]["CodeRunnerError"];
        } | {
            /** @constant */
            event: "result";
            data: {
                stdout: string;
                stderr: string;
                /** Format: int64 */
                exit_code?: number | null;
                timeout: boolean;
            };
        };
        CodeRunnerError: {
            message: string;
            logs: string;
            /** @constant */
            error: "build_failed";
        } | {
            message: string;
            /** @constant */
            error: "docker";
        } | {
            message: string;
            image_tag: string;
            /** @constant */
            error: "function_image_not_found";
        };
        CreateFunctionInput: {
            /** @description Name of the function to create */
            name: string;
            /** @description Language of the function */
            language: components["schemas"]["CodeRunnerLanguage"];
        };
        FunctionItem: {
            name: string;
            info: components["schemas"]["FunctionInfo"];
        };
        /** @description Selected function info stored in Redis */
        FunctionInfo: {
            lang: components["schemas"]["CodeRunnerLanguage"];
            description?: string | null;
            status: components["schemas"]["FunctionStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: string;
        };
        /** @description Build status of the function */
        FunctionStatus: {
            /** @constant */
            type: "not_built";
        } | {
            /** @constant */
            type: "building";
        } | ({
            /** @constant */
            type: "error";
        } & components["schemas"]["CodeRunnerError"]) | {
            /** @description The image tag of the function */
            tag: string;
            /** @description The image id of the function */
            id: string;
            /** @constant */
            type: "ready";
        };
        FunctionNamePath: {
            name: string;
        };
        /** @description Full function info stored in Redis */
        FunctionDetail: {
            code: string;
            lang: components["schemas"]["CodeRunnerLanguage"];
            description?: string | null;
            dependencies?: string | null;
            status: components["schemas"]["FunctionStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: string;
        };
        UpdateFunctionInput: {
            /** @description New code for the function */
            code: string;
            /** @description An optional description for the function */
            description?: string | null;
            /**
             * @description Dependencies for the code execution. Versions and features can be specified
             *     depending on the language's package manager.
             * @example [
             *       "lodash"
             *     ]
             * @example [
             *       "serde=1.0",
             *       "tokio=1.0",
             *       "--features",
             *       "serde/derive"
             *     ]
             */
            dependencies?: string[] | null;
        };
        RunFunctionInput: {
            /** @description Input to the function */
            input: string;
            /**
             * Format: uint32
             * @description Timeout for the code execution in seconds
             * @default 60
             */
            timeout: number;
            /**
             * Format: uint32
             * @description Memory limit for the code execution in megabytes
             * @default 256
             */
            mem_limit_mb: number;
            /**
             * Format: float
             * @description CPU quota (1.0 = 1 CPU core)
             * @default 0.5
             */
            cpu_limit: number;
        };
        RunFunctionOutput: {
            stdout: string;
            stderr: string;
            /** Format: int64 */
            exit_code?: number | null;
            timeout: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Options for the code runner */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRunnerInput"];
            };
        };
        responses: {
            /** @description Chunk of the code runner stream output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["CodeRunnerChunk"];
                    "application/jsonl": components["schemas"]["CodeRunnerChunk"];
                };
            };
        };
    };
    list_functions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionItem"][];
                };
            };
        };
    };
    create_function: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFunctionInput"];
            };
        };
        responses: {
            /** @description Chunk of the code runner stream output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["CodeRunnerChunk"];
                    "application/jsonl": components["schemas"]["CodeRunnerChunk"];
                };
            };
        };
    };
    get_function: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Selected function info stored in Redis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionInfo"];
                };
            };
        };
    };
    get_function_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full function info stored in Redis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDetail"];
                };
            };
        };
    };
    update_function: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFunctionInput"];
            };
        };
        responses: {
            /** @description Chunk of the code runner stream output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["CodeRunnerChunk"];
                    "application/jsonl": components["schemas"]["CodeRunnerChunk"];
                };
            };
        };
    };
    run_function: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunFunctionInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunFunctionOutput"];
                };
            };
        };
    };
    run_function_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunFunctionInput"];
            };
        };
        responses: {
            /** @description Chunk of the code runner stream output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["CodeRunnerChunk"];
                    "application/jsonl": components["schemas"]["CodeRunnerChunk"];
                };
            };
        };
    };
}
