FROM {{ image }}

ENV PYTHONUNBUFFERED=1
ENV PYTHONUSERBASE="/opt/python"
ENV PATH="/opt/python/bin:$PATH"

RUN mkdir -p /opt/python && chown {{ uid_gid }} /opt/python

{{ set_user_and_home_dir }}

{% if dependencies %}
RUN pip install --user --no-cache-dir {{ dependencies }}
{% endif %}

{{ set_build_id }}

COPY --chown={{ uid_gid }} . .

CMD ["python", "{{ main_file }}"]
