FROM {{ image }}

ENV PYTHONUNBUFFERED=1
ENV PYTHONUSERBASE="/opt/python"
ENV PATH="/opt/python/bin:$PATH"

RUN mkdir -p /opt/python && chown {{ uid_gid }} /opt/python

{{ set_user_and_home_dir }}

{% if dependencies %}
RUN pip install --user --no-cache-dir {{ dependencies }}
{% endif %}

COPY --chown={{ uid_gid }} {{ main_file }} .
{% if fn_file %}
COPY --chown={{ uid_gid }} {{ fn_file }} .
{% endif %}
{% for file in files %}
COPY --chown={{ uid_gid }} {{ file.path }} ./files/{{ file.path }}
{% endfor %}

CMD ["python", "{{ main_file }}"]
