FROM {{ image }}

ENV PNPM_HOME="/opt/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN mkdir -p /opt/pnpm && chown {{ uid_gid }} /opt/pnpm
RUN npm install -g --quiet pnpm@9

{{ set_user_and_home_dir }}

RUN pnpm init
RUN pnpm pkg set type="module"
{% if dependencies %}
RUN pnpm install {{ dependencies }}
{% endif %}

{{ set_build_id }}

COPY --chown={{ uid_gid }} . .

CMD ["node", "{{ main_file }}"]
