FROM {{ image }}
RUN apt-get update -qq && apt-get install -y -qq pkg-config libssl-dev ca-certificates && apt-get clean

{{ set_user_and_home_dir }}

RUN cargo init --name temp
{% if dependencies %}
RUN cargo add {{ dependencies }}
{% endif %}

RUN cargo build

{{ set_build_id }}

COPY --chown={{ uid_gid }} . .
RUN mv {{ main_file }} src/{{ main_file }}
{% if fn_file %}
RUN mv {{ fn_file }} src/{{ fn_file }}
{% endif %}

RUN touch src/{{ main_file }}
RUN cargo build

CMD ["./target/debug/temp"]
