FROM {{ image }}

ENV PNPM_HOME="/opt/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN mkdir -p /opt/pnpm && chown {{ uid_gid }} /opt/pnpm
RUN npm install -g pnpm@9

{{ set_user_and_home_dir }}

RUN pnpm init
RUN pnpm install tsx {{ dependencies }}

COPY --chown={{ uid_gid }} {{ main_file }} .
{% if fn_file %}
COPY --chown={{ uid_gid }} {{ fn_file }} .
{% endif %}
{% for file in files %}
COPY --chown={{ uid_gid }} {{ file.path }} ./files/{{ file.path }}
{% endfor %}

CMD ["pnpm", "tsx", "{{ main_file }}"]
