FROM {{ image }}

{% if dependencies %}
RUN apk add --no-cache {{ dependencies }}
{% endif %}

{{ set_user_and_home_dir }}

COPY --chown={{ uid_gid }} {{ main_file }} .
{% if fn_file %}
COPY --chown={{ uid_gid }} {{ fn_file }} .
RUN chmod +x {{ fn_file }}
{% endif %}
{% for file in files %}
COPY --chown={{ uid_gid }} {{ file.path }} ./files/{{ file.path }}
{% endfor %}

CMD ["bash", "{{  main_file }}"]
