FROM {{ image }}

{% if dependencies %}
RUN apk add --no-cache {{ dependencies }}
{% endif %}

{{ set_user_and_home_dir }}

{{ set_build_id }}

COPY --chown={{ uid_gid }} . .
{% if fn_file %}
RUN chmod +x {{ fn_file }}
{% endif %}

CMD ["bash", "{{  main_file }}"]
